Add requests manager
mate-academy/node_accounting-app-v2 pull request #391
Opened 2023-10-17 20:48 UTC by neovendano

2023-10-18 13:04 UTC, Orpheus29 approved these changes
Good job!

2023-10-19 08:21 UTC, Moroz-Dmytro requested changes

2023-10-19 08:21 UTC, Moroz-Dmytro commented on src/controllers/expenses.controller.js
> +  if (!id) {
Better to do this check before searching expense

2023-10-19 08:21 UTC, Moroz-Dmytro commented on src/controllers/expenses.controller.js
> +      expense => categories.includes(expense.category)
if there are no `categories` in search params we will get `undefined`
if only 1 `categories` we will get just value (....?categories=1)
And if we have many categories we will get array of values (....?categories=1&categories=2&categories=3)

![image](https://github.com/mate-academy/node_accounting-app-v2/assets/86789161/ea010564-92a2-4116-9fcf-a66739d6d01f)

You code will crash if you have only 1 category

2025-07-28 10:41 UTC, closed without merging